### PR TITLE
Bug/breadcrumps

### LINKED ISSUE #292: Vuestic-breadcrumbs broken
I have a following page structure:
Home > Users > Add user

Corresponding URL:
myapp.loc/#/admin/users/new

Link on "Home" is true, leads to dashboard;
Link on "Add user" is true, leads to current page;
Link on "Users" is broken - is suggests URL like "myapp.loc/#/admin/users/users", but it should be "myapp.loc/#/admin/users"

### PR DESCRIPTION
**Pull request by AlexanderBoriskin**
close #292

### CODE REVIEW

File: src/components/admin/app-breadcrumbs/Breadcrumbs.js [hunk 1]
```diff
@@ -68,81 +68,91 @@ export default {
...
         },
         {
-          path: 'icons',
-          displayName: 'menu.icons'
+          name: 'icons',
+          displayName: 'menu.icons',
+          children: [
+            {
+              displayName: 'concrete',
+              name: '',
```
Comment (asvae) [inline src/components/admin/app-breadcrumbs/Breadcrumbs.js]: And what this does?

Comment (asvae) [inline src/components/admin/app-breadcrumbs/Breadcrumbs.js]: And what this does?

Comment (AlexanderBoriskin) [reply src/components/admin/app-breadcrumbs/Breadcrumbs.js]: instead of using paths in breadcrumbs object i decided to use name of these routes, what helps to solve problem with incorrect paths

maybe "routeName" is more suitable here?

Comment (asvae) [reply src/components/admin/app-breadcrumbs/Breadcrumbs.js]: Why name is "" then? Also ":name"?
