### PR TITLE
Fix/va-slider

### LINKED ISSUE #522: Slider component bugs
@AlexanderBoriskin we discussed specifics in discord.

Most prominent example:

### PR DESCRIPTION
**Pull request by nastassiadanilova**
- fix #522 
- remove bootstrap classes (fix book:serve errors)

### CODE REVIEW

File: src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue [hunk 1]
```diff
@@ -108,35 +106,34 @@
     </div>
     <span
       v-if="iconRight"
-      class="va-slider__inverse-label title">
+      class="va-slider__label va-slider__inverse-label">
       <va-icon :icon="iconRight" :color="color" :size="16"/>
```
Comment (asvae) [inline src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue]: image

File: src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue [hunk 2]
```diff
@@ -1,40 +1,38 @@
 <template>
```
Comment (asvae) [inline src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue]: image

File: src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue [hunk 3]
```diff
@@ -443,8 +439,19 @@ export default {
       this.setTransform()
 
       if (pos >= range[0] && pos <= range[1]) {
```
Comment (asvae) [inline src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue]: What is `pos`?

File: src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue [hunk 4]
```diff
@@ -454,8 +461,9 @@ export default {
     setTransform () {
       if (this.isRange) {
         const slider = this.currentSlider
-        const val0 = ((this.value[0] - this.min) / (this.max - this.min)) * 100
-        const val1 = ((this.value[1] - this.min) / (this.max - this.min)) * 100
+        const difference = 100 / (this.max - this.min)
+        const val0 = (this.value[0] - this.min) * difference
+        const val1 = (this.value[1] - this.min) * difference
         const processSize = `${val1 - val0}%`
         const processPos = `${val0}%`
```
Comment (asvae) [inline src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue]: processPosition?

File: src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue [hunk 5]
```diff
@@ -543,20 +553,95 @@ export default {
...
+    flex-direction: row;
+    min-height: 2.25rem;
+    margin-top: 0.2rem;
+    margin-bottom: 1.5rem;
+
+    &--after {
+      margin-left: 8.33333%;
+    }
+
+    .input-group {
```
Comment (asvae) [inline src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue]: We probably don't need that.

File: src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue [hunk 6]
```diff
@@ -543,20 +553,95 @@ export default {
...
+      transition: all 0.28s ease;
+      box-shadow: none;
+      height: 1.9rem;
+      font-family: inherit;
+      &:focus {
+        outline: none;
+      }
+    }
+
+    .control-label {
```
Comment (asvae) [inline src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue]: And we don't need that.

File: src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue [hunk 7]
```diff
@@ -592,6 +677,11 @@ export default {
         left: 50%;
         transform: translate(-50%, -100%);
         user-select: none;
+        font-size: .625rem;
```
Comment (asvae) [inline src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue]: Not exactly sure what this does.

File: src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue [hunk 8]
```diff
@@ -1,40 +1,38 @@
...
+      class="va-slider__label">
       <va-icon :icon="icon" :color="colorComputed" :size="16"/>
     </span>
     <div
-      :class="{ 'flex offset--xs1 offset--lg1': range && withInput }"
-      class="va-slider__container d-flex align--center"
+      :class="{ 'va-slider__container--with-input': range && withInput }"
+      class="va-slider__container"
       @click="wrapClick"
       ref="elem"
```
Comment (asvae) [inline src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue]: sliderContainer?

File: src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue (hunk 2 above)
Comment (asvae) [reply src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue]: @nastassiadanilova any updates on that?

File: src/components/ui/sliders/Sliders.vue [hunk 9]
```diff
@@ -178,6 +178,15 @@
               v-model="value2"
```
Comment (asvae) [inline src/components/ui/sliders/Sliders.vue]: Page is overloaded.

image

File: src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue [hunk 10]
```diff
@@ -1,42 +1,26 @@
 <template>
```
Comment (asvae) [inline src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue]: image

Comment (asvae) [inline src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue]: image
