### PR TITLE
Fix working in IE11 

### LINKED ISSUE #663: IE 11/Edge
Bug Report - Both IE 11 and Edge comes up blank when browsing to https://vuestic.epicmax.co

Only the chat box pops up on both browsers.

### PR DESCRIPTION
**Pull request by Kreezag**
## close #663 

Fix for IE11
Remove unused dependencies
Update dependencies for work vuestic-admin in ie11

</details>

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: .browserslistrc [hunk 1]
```diff
@@ -1,3 +1,4 @@
 > 1%
 last 2 versions
+ie 11
 not ie <= 8
```
Comment (asvae) [inline .browserslistrc]: This is not needed. We only support ie 11

File: src/services/vuestic-ui/components.js [hunk 2]
```diff
@@ -0,0 +1,9 @@
+import VuesticPlugin from 'vuestic-ui/src/components/vuestic-plugin'
```
Comment (asvae) [inline src/services/vuestic-ui/components.js]: There is not much of a point grouping these instead of importing them directly.
But that's a minor thing.

Comment (Kreezag) [reply src/services/vuestic-ui/components.js]: One point has a value if we will do refactor in the future. And it's better for understanding.
