### PR TITLE
Fix/navbar poblems

### LINKED ISSUE #580: Navbar problems
## Too important

image
- [x] This link is not clickable.

## Not too important

```scss
$nav-shape-bg: #0a43af;
```
- [x] Should work with theme. You can check how to handle color from `src/vuestic-theme/vuestic-components/va-button/VaButton.vue:158`

`src/vuestic-theme/vuestic-components/va-navbar/VaNavbar.vue:15`
```html
    <div class="va-navbar__content va-row">
      <div
        class="va-navbar__center flex offset--lg3 offset--md3 lg5 flex md4 va-row flex-center">
        <slot name="center"></slot>
      </div>
```
- [x] Classes for grid work like this: `.va-row > .flex > .va-row`. Not `.va-row > .va-row`. Also 2  `.flex`. Also check other relevant components. Seen this in a couple of places.

`src/vuestic-theme/vuestic-components/va-navbar/VaNavbar.vue:2`
```html
  <nav class="va-navbar position-relative">
```
- [ ] ~`position-relative` is global bootstrap style. Please also remove other bootstrap global styles from related components. (I noticed `.flex-nowrap` but likely there is something else).~ not relevant for navbar

`src/components/admin/app-navbar/components/dropdowns/LanguageDropdown.vue:8`
```html
      <div class="language-dropdown__item va-row align--center"
```
- [x] We have `.d-flex` if you just need flex. `.va-row` is for grid.

`src/components/admin/app-navbar/components/dropdowns/ProfileDropdown.vue:52`
```js
toggleVisibility (val) {
      this.isShown = val
    },
```
-  ~[ ]~ **not relevant** What is it for? Please comment.

`src/components/admin/app-navbar/components/dropdowns/SettingsDropdown.vue:36`
```js
 return {
      options: [
        { label: this.$t('dashboard.topBarButton'), value: 'true' },
        { label: this.$t('dashboard.sideBarButton'), value: 'false' },
      ],
    }
```
- [x] Why not use `false` and `true` instead? Also, why `this.$emit('update:navbarView', navbarView === 'true')`? Also `navbarView` prop is Boolean, so using string does not make a lot of sense.

`src/components/admin/app-navbar/AppNavbar.vue:25`
```html
<!--<settings-dropdown-->
        <!--class="va-navbar__item"-->
        <!--:navbar-view.sync="navbarViewProxy"-->
      <!--/>-->
```
- [x] Settings dropdown is commented out. Please leave a comment if that's a temporary decision or remove it altogether.

`src/vuestic-theme/vuestic-sass/resources/_variables.scss:267`
```scss
$dropdown-item-height: 40px;
$dropdown-menu-padding-y: 10px;
```
-~[ ]~ **not relevant for navbar** Rem? Also some `px` values nearby.

### PR DESCRIPTION
**Pull request by Kreezag**
## Description

Close #580 
Navbar refactor
Remove unused header components (app-topbar, settings-dropdown)
Revert iconsets to vuesic-admin from vuestic ui

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

File: src/components/admin/app-navbar/AppNavbar.vue [hunk 1]
```diff
@@ -17,57 +30,61 @@
...
-import ProfileDropdown from './components/dropdowns/ProfileDropdown'
-import NotificationDropdown from './components/dropdowns/NotificationDropdown'
-import MessageDropdown from './components/dropdowns/MessageDropdown'
-import SettingsDropdown from './components/dropdowns/SettingsDropdown'
-import ColorDropdown from './components/dropdowns/ColorDropdown'
+import VaIconVuestic from '../../../iconset/VaIconVuestic'
+import AppNavbarActions from './components/AppNavbarActions'
+import { hex2hsl } from '../../../services/color-functions'
+
+// TODO: need to update for all color-functions
```
Comment (asvae) [inline src/components/admin/app-navbar/AppNavbar.vue]: Maybe makes sense to finish that in scope of current PR?

File: src/components/admin/app-navbar/components/AppNavbarActions.vue [hunk 2]
```diff
@@ -0,0 +1,80 @@
+<template>
+  <div class="app-navbar-actions">
+      <color-dropdown class="app-navbar-actions__item"/>
```
Comment (asvae) [inline src/components/admin/app-navbar/components/AppNavbarActions.vue]: 2 tabs?
Feel free to ignore, I'm just not sure how this got past linter.

File: src/components/admin/app-navbar/AppNavbar.vue (hunk 1 above)
Comment (Kreezag) [reply src/components/admin/app-navbar/AppNavbar.vue]: Yeap. It's a good idea!
