### PR TITLE
Bug/sidebar

### LINKED ISSUE #283: Click on sidebar category hides sidebar
- [ ] and it shouldn't

image

### PR DESCRIPTION
**Pull request by AlexanderBoriskin**
close #283 #285 #287

### CODE REVIEW

File: src/router/index.js [hunk 1]
```diff
@@ -29,6 +29,7 @@ const EmptyParentComponent = {
 }
 
 export default new Router({
+  mode: 'history',
```
Comment (jean-moldovan) [inline src/router/index.js]: Not sure if we need to enable it by default.

@asvae , Maybe something that we might want to add to wiki?

File: src/sass/_icons-styles.scss [hunk 2]
```diff
@@ -1,4 +1,4 @@
-@import url(https://weloveiconfonts.com/api/?family=brandico|entypo|fontelico|iconicfill|iconicstroke|maki|openwebicons|typicons|zocial);
+@import url(http://weloveiconfonts.com/api/?family=brandico|entypo|fontelico|iconicfill|iconicstroke|maki|openwebicons|typicons|zocial);
```
Comment (jean-moldovan) [inline src/sass/_icons-styles.scss]: Why not https?

File: src/vuestic-theme/vuestic-directives/Layout.js [hunk 3]
```diff
@@ -4,13 +4,13 @@ export default {
     let navbar = el.querySelector('.vuestic-navbar')
     let sidebar = el.querySelector('.vuestic-sidebar')
 
-    const desktopWidth = 992
+    const mobileWidth = 415
```
Comment (jean-moldovan) [inline src/vuestic-theme/vuestic-directives/Layout.js]: why 415?

File: src/router/index.js (hunk 1 above)
Comment (AlexanderBoriskin) [reply src/router/index.js]: it helps to prevent "#" in url (i saw this solution on one of the forums), related issue:
https://github.com/epicmaxco/vuestic-admin/issues/285

File: src/sass/_icons-styles.scss (hunk 2 above)
Comment (AlexanderBoriskin) [reply src/sass/_icons-styles.scss]: without changing url icons are not displayed on the Vuestic Icons Page, related issue:
https://github.com/epicmaxco/vuestic-admin/issues/287

File: src/vuestic-theme/vuestic-directives/Layout.js (hunk 3 above)
Comment (AlexanderBoriskin) [reply src/vuestic-theme/vuestic-directives/Layout.js]: it is a maximum mobile width (i check it from all mobile devices in browser), that helps us to divide sidebar behaviour between mobile and desktop version of app, related issue:
https://github.com/epicmaxco/vuestic-admin/issues/283

File: src/router/index.js (hunk 1 above)
Comment (jean-moldovan) [reply src/router/index.js]: Doesn't seem related. In my understanding the issue is that if you click on a category and then refresh the page you get redirected to the main page. Am I correct?

Comment (jean-moldovan) [reply src/router/index.js]: Let's say you are on `https://vuestic.epicmax.co/#/admin/forms/form-elements`. If you click on a category the url goes `https://vuestic.epicmax.co/#/` which is incorrect. Url should not change.

File: src/sass/_icons-styles.scss (hunk 2 above)
Comment (jean-moldovan) [reply src/sass/_icons-styles.scss]: meh, https://github.com/TimPietrusky/weloveiconfonts/issues/42
@asvae , what do we do, use http?

File: src/router/index.js (hunk 1 above)
Comment (AlexanderBoriskin) [reply src/router/index.js]: oh, i understand. tnx!

File: src/vuestic-theme/vuestic-directives/Layout.js (hunk 3 above)
Comment (jean-moldovan) [reply src/vuestic-theme/vuestic-directives/Layout.js]: ok, please check with @smartapant

File: src/sass/_icons-styles.scss (hunk 2 above)
Comment (asvae) [reply src/sass/_icons-styles.scss]: @jean-moldovan Sure. Tiny hack.

File: src/router/index.js (hunk 1 above)
Comment (asvae) [reply src/router/index.js]: Mode history requires quite specific server config. And we want vuestic to be simple to start.
